apiVersion: v2
name: runpod-kubelet
description: A Helm chart for deploying RunPod Virtual Kubelet
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/bsvogler/k8s-runpod-kubelet
sources:
  - https://github.com/bsvogler/k8s-runpod-kubelet
maintainers:
  - name: bsvogler
keywords:
  - runpod
  - virtual-kubelet
  - gpu
  - kubernetes