apiVersion: v1
kind: Node
metadata:
  name: runpod-virtual-node
  labels:
    kubernetes.io/hostname: runpod-virtual-node
    runpod.io/virtual: "true"
  annotations:
    node.kubernetes.io/exclude-from-external-load-balancers: "true"
spec:
  taints:
  - key: runpod.io/virtual
    effect: NoSchedule
status:
  conditions:
  - type: Ready
    status: "True"
  allocatable:
    cpu: "0"
    memory: "0"
    pods: "100"
    nvidia.com/gpu: "0"
  capacity:
    cpu: "0"
    memory: "0"
    pods: "100"
    nvidia.com/gpu: "0"
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runpod-virtual
handler: runpod-virtual
scheduling:
  nodeSelector:
    runpod.io/virtual: "true"
  tolerations:
  - key: runpod.io/virtual
    operator: Exists
    effect: NoSchedule
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runpod-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runpod-controller
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runpod-controller
subjects:
- kind: ServiceAccount
  name: runpod-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: runpod-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runpod-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runpod-controller
  template:
    metadata:
      labels:
        app: runpod-controller
    spec:
      serviceAccountName: runpod-controller
      containers:
      - name: controller
        image: bsvogler/runpod-controller:latest
        args:
        - "--reconcile-interval=30"
        - "--pending-job-threshold=5"
        - "--max-gpu-price=0.5"
        - "--health-server-address=:8080"
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        env:
        - name: RUNPOD_KEY
          valueFrom:
            secretKeyRef:
              name: runpod-controller-secrets
              key: RUNPOD_KEY
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi