{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "runpod-kubelet.fullname" . }}
  labels:
    {{- include "runpod-kubelet.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runpod-kubelet.serviceAccountName" . }}
    namespace: {{ .Values.kubelet.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "runpod-kubelet.fullname" . }}
{{- end }}