{{- if and (not .Values.runpod.existingSecret) (or .Values.runpod.apiKey .Values.conduit.apiToken) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runpod-kubelet.fullname" . }}
  namespace: {{ .Values.kubelet.namespace }}
  labels:
    {{- include "runpod-kubelet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.runpod.apiKey }}
  RUNPOD_API_KEY: {{ .Values.runpod.apiKey | quote }}
  {{- end }}
  {{- if .Values.conduit.apiToken }}
  CONDUIT_API_TOKEN: {{ .Values.conduit.apiToken | quote }}
  {{- end }}
{{- end }}