name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and tag Docker image
      run: |
        TAG=$(date +%s)
        echo "TAG=$TAG" >> $GITHUB_ENV
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build . --file Dockerfile --tag bsvogler/gpu-runpod-controller:$TAG --tag ghcr.io/$REPO_OWNER/gpu-runpod-controller:$TAG --tag ghcr.io/$REPO_OWNER/gpu-runpod-controller:latest
        
    - name: Push to GitHub Container Registry
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPO_OWNER/gpu-runpod-controller:${{ env.TAG }}
        docker push ghcr.io/$REPO_OWNER/gpu-runpod-controller:latest
