name: Docker Image CI
permissions:
  packages: write
  contents: read
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and tag Docker image
      run: |
        TAG=$(date +%s)
        echo "TAG=$TAG" >> $GITHUB_ENV
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        if [ "${{ github.ref }}" = "refs/heads/master" ]; then
          docker build . --file Dockerfile --tag bsvogler/runpod-kubelet:$TAG --tag ghcr.io/$REPO_OWNER/runpod-kubelet:$TAG --tag ghcr.io/$REPO_OWNER/runpod-kubelet:latest
        else
          docker build . --file Dockerfile --tag bsvogler/runpod-kubelet:$TAG --tag ghcr.io/$REPO_OWNER/runpod-kubelet:$TAG --tag ghcr.io/$REPO_OWNER/runpod-kubelet:${{ github.ref_name }}
        fi
        
    - name: Push to GitHub Container Registry
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPO_OWNER/runpod-kubelet:${{ env.TAG }}
        if [ "${{ github.ref }}" = "refs/heads/master" ]; then
          docker push ghcr.io/$REPO_OWNER/runpod-kubelet:latest
        else
          docker push ghcr.io/$REPO_OWNER/runpod-kubelet:${{ github.ref_name }}
        fi
