name: Publish Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'helm/**'
      - '.github/workflows/helm-publish.yml'
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
        
      - name: Package Helm chart
        run: |
          helm package ./helm/runpod-kubelet
          ls -la *.tgz
          
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Push Helm chart using OCI
        run: |
          CHART_VERSION=$(grep '^version:' ./helm/runpod-kubelet/Chart.yaml | awk '{print $2}')
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          CHART_NAME="runpod-kubelet"
          
          echo "Chart version: ${CHART_VERSION}"
          echo "Repository: ghcr.io/${REPO_OWNER}/${CHART_NAME}"
          
          # Push the chart
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${REPO_OWNER}